file(SHA256 "${KERNEL}" kernel_hash)
file(SHA256 "${RUNNER}" runner_hash)
file(SHA256 "${BINARY}" binary_hash)
file(SHA256 "${COMPILER}" compiler_hash)
foreach(field ARCH COMPILER FLAGS)
    string(REPLACE "\\" "\\\\" ${field} "${${field}}")
    string(REPLACE "\"" "\\\"" ${field} "${${field}}")
    string(REPLACE "\n" "\\n" ${field} "${${field}}")
endforeach()
file(WRITE "${BINARY}.build.json"
    "{\n  \"kernel_sha256\": \"${kernel_hash}\",\n  \"runner_sha256\": \"${runner_hash}\",\n  \"binary_sha256\": \"${binary_hash}\",\n  \"compiler_sha256\": \"${compiler_hash}\",\n  \"arch\": \"${ARCH}\",\n  \"compiler\": \"${COMPILER}\",\n  \"flags\": \"${FLAGS}\"\n}\n")
